# Generated by Django 3.2.5 on 2021-07-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20210703_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Отчество'),
        ),
    ]
